version: "3.9"
services:
  app:
    build:
      context: .
      # use same Dockerfile (app/Dockerfile exists at repo root)
    container_name: patternos_app_prod
    env_file:
      - .env
    environment:
      - ENV=prod
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./patternos.db}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: patternos_frontend_prod
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-patternos}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
